image: registry.gitlab.com/pages/hugo/hugo_extended:0.126.1

variables:
  HUGO_ENV: production

default:
  before_script:
    - apk add --no-cache go curl bash nodejs

pages:
  script:
    - git submodule update --init --recursive
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
